"""
Script for pre-preprocessing the raw tweets collected using GetOldTweets3.

Input: csv file generated by GetOldTweets3
Output: ready to be labelled csv file containing only important columns including an empty "polarity" column
"""

import pandas as pd


# convert csv to a pandas dataframe
tweets_df = pd.read_csv("data/raw-dataset/training-dataset/SWA_2-0_LEI_neg.csv")

# drop unnecessary columns
tweets_df = tweets_df.drop(labels=["to", "replies", "retweets", "favorites", "geo", "mentions", "hashtags", "permalink"], axis=1)

# add empty "polarity" column
tweets_df["polarity"] = ""

# reorder columns
tweets_df = tweets_df.reindex(columns=["date", "id", "username", "polarity", "text"])

tweets_df.to_csv("data/labelled-dataset/training-dataset/SWA_2-0_LEI_neg.csv", index=False)
